# Generated by Django 5.0.6 on 2024-06-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ifound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=60)),
                ('what', models.CharField(max_length=60)),
                ('where', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ilost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=60)),
                ('what', models.CharField(max_length=60)),
                ('where', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=60)),
            ],
        ),
    ]
