# Generated by Django 5.0.6 on 2024-07-01 02:11

import busqueda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0002_alter_ifound_when_alter_ilost_when'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ifound',
            options={'ordering': ['when', 'what'], 'verbose_name': 'Found Property', 'verbose_name_plural': 'Found Properties'},
        ),
        migrations.AlterModelOptions(
            name='ilost',
            options={'ordering': ['when', 'what'], 'verbose_name': 'Lost Property', 'verbose_name_plural': 'Lost Properties'},
        ),
        migrations.AlterField(
            model_name='ilost',
            name='when',
            field=models.DateField(validators=[busqueda.models.validate_past_date]),
        ),
    ]
