# Generated by Django 5.0.6 on 2024-07-03 06:05

import busqueda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0004_ifound_return_owner_ilost_return_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('testimonio', models.CharField(max_length=900)),
            ],
        ),
        migrations.AlterField(
            model_name='ifound',
            name='when',
            field=models.DateField(validators=[busqueda.models.validate_past_date]),
        ),
    ]
