# Generated by Django 5.0.6 on 2024-07-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0006_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='apellido',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='ciudad',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='nombre',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonio',
            new_name='testimonial',
        ),
    ]
