# Generated by Django 5.0.6 on 2024-07-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0007_rename_apellido_testimonial_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ifound',
            old_name='return_owner',
            new_name='returned_owner',
        ),
        migrations.RenameField(
            model_name='ilost',
            old_name='return_owner',
            new_name='returned_owner',
        ),
    ]
