# Generated by Django 5.0.6 on 2024-07-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0010_remove_contact_fullname_remove_contact_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ifound',
            options={},
        ),
        migrations.AddField(
            model_name='ifound',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: Complete a short description of item', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ifound',
            name='where',
            field=models.CharField(choices=[('Lobby', 'Lobby'), ('Tonic bar', 'Tonic bar'), ('Graze: Breakfast', 'Graze: Breakfast'), ('Underwater Observatory', 'Underwater Observatory'), ('North end Pool', 'North end Pool'), ('Salti: Restaurant', 'Salti: Restaurant'), ('Infinity: Restaurant', 'Infinity: Restaurant'), ("Kid's club", "Kid's club"), ('Living reef center', 'Living reef center'), ('The Shake/Candy shop', 'The Shake/Candy shop'), ('Canopy wing: corridor', 'Canopy wing: corridor'), ('Driftwood wing: corridor', 'Driftwood wing: corridor'), ('Harbour wing: corridor', 'Harbour wing: corridor'), ('Transit Lounge', 'Transit Lounge'), ('Ferry', 'Ferry'), ('South end pool', 'South end pool'), ('Water sports', 'Water sports'), ('My room', 'My room'), ("Lover's Cove", "Lover's Cove"), ('Rain forest walk', 'Rain forest walk'), ('Tennis/Basquet court', 'Tennis/Basquet court'), ("I don't know", "I don't know")], help_text='Select a place where you lost your item', max_length=60),
        ),
    ]
