# Generated by Django 5.0.6 on 2024-07-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0011_alter_ifound_options_ifound_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifound',
            name='photo',
            field=models.ImageField(default='', help_text='Opcional: load a photo of the item', upload_to=''),
        ),
        migrations.AddField(
            model_name='ilost',
            name='photo',
            field=models.ImageField(default='', help_text='Opcional: load a photo of the item', upload_to=''),
        ),
    ]
