# Generated by Django 5.0.6 on 2024-07-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0012_ifound_photo_ilost_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ifound',
            options={'ordering': ['when', 'what'], 'verbose_name': 'Found Property', 'verbose_name_plural': 'Found Properties'},
        ),
    ]
