# Generated by Django 5.0.6 on 2024-07-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0013_alter_ifound_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifound',
            name='photo',
            field=models.ImageField(blank=True, help_text='Opcional: load a photo of the item', null=True, upload_to='found_photos/'),
        ),
        migrations.AlterField(
            model_name='ilost',
            name='photo',
            field=models.ImageField(blank=True, help_text='Opcional: load a photo of the item', null=True, upload_to='lost_photos/'),
        ),
    ]
