# Generated by Django 5.0.6 on 2024-07-18 09:47

import busqueda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0015_alter_testimonial_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilost',
            name='name_booking',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='ilost',
            name='room_number',
            field=models.IntegerField(blank=True, null=True, validators=[busqueda.models.validate_four_digits]),
        ),
    ]
