# Generated by Django 5.0.6 on 2024-07-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0016_ilost_name_booking_ilost_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilost',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ilost',
            name='model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ilost',
            name='size',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
