# Generated by Django 5.0.6 on 2024-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0019_alter_ilost_name_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilost',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
