# Generated by Django 5.0.6 on 2024-07-20 06:02

import busqueda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0021_alter_ilost_email_alter_ilost_name_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilost',
            name='room_number',
            field=models.IntegerField(validators=[busqueda.models.validate_four_digits]),
        ),
    ]
