# Generated by Django 5.0.6 on 2024-07-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0022_alter_ilost_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilost',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ilost',
            name='name_booking',
            field=models.CharField(max_length=60),
        ),
    ]
