# Generated by Django 5.0.6 on 2024-07-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0023_alter_ilost_email_alter_ilost_name_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['firstName'], 'verbose_name': 'Testimonial'},
        ),
    ]
